import{S as m,i}from"./assets/vendor-8d97032d.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function t(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();function y(o){const r=document.querySelector(".gallery");r.innerHTML+=o.map(t=>`
        <li class="gallery-item">
            <a href="${t.largeImageURL}" data-lightbox="gallery">
                <img src="${t.webformatURL}" alt="${t.tags}" class="image-card-image">
                <div class="image-card-details">
                    <span class="image-card-likes"><span class="bold">Likes:</span><br>${t.likes}</span>
                    <span class="image-card-views"><span class="bold">Views:</span><br>${t.views}</span>
                    <span class="image-card-comments"><span class="bold">Comments:</span><br>${t.comments}</span>
                    <span class="image-card-downloads"><span class="bold">Downloads:</span><br>${t.downloads}</span>
                </div>
            </a>
        </li>
    `).join(""),g();const s=document.getElementById("load-more-button");s.style.display="block"}function g(){const o={captions:!0,captionType:"attr",captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.8};new m(".gallery a",o)}function f(){i.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topCenter"})}function h(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const c=document.getElementById("loader"),b=document.querySelector(".gallery");let d=1,n;async function w(o,r){o.preventDefault();const t=r.querySelector("#search-form-input").value.trim();if(t===""){i.warning({title:"Caution",message:"The search field cannot be empty!"});return}c.style.display="block",b.innerHTML="",d=1,n=document.getElementById("load-more-button"),await u(t)}async function I(){c.style.display="block",d++,n=document.getElementById("load-more-button");const r=document.getElementById("search-form-input").value.trim();await u(r)}async function u(o){let s=`https://pixabay.com/api/?key=42176348-9192a588252a9fae2debe28a6&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${d}&per_page=15`;try{const e=await(await fetch(s)).json();e.hits.length>0?(y(e.hits),e.hits.length<15?n.style.display="none":n.style.display="block",h()):(i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),n.style.display="none")}catch(t){f(),console.error("Fetch error:",t)}finally{c.style.display="none"}}const p=document.getElementById("search-form"),v=document.getElementById("load-more-button");p.addEventListener("submit",o=>w(o,p));v.addEventListener("click",I);
//# sourceMappingURL=commonHelpers.js.map
